
spring:
    application.name: Learning
    datasource:
        url: jdbc:postgresql://localhost:5432/learning
        username: learning
        password: learning
        driver-class-name: org.postgresql.Driver
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yml
    jpa:
        show-sql: true



